version: "3.9"

services:
  app:
    container_name: jira-app
    image: jira
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/jira
      - DATASOURCE_USERNAME=jira
      - DATASOURCE_PASSWORD=JiraRush
    networks:
      - backend

#    env_file:
#      - secret.env
  db:
    container_name: postgres-db
    image: postgres:11
    environment:
      POSTGRES_USER: 'jira'
      POSTGRES_PASSWORD: 'JiraRush'
      POSTGRES_DB: 'jira'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
#      interval: 2s
#      timeout: 30s
#      retries: 10
    networks:
      - backend

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx//nginx.conf:ro
#      - ./resources:/opt/jirarush/resources:ro
    networks:
      - backend
#    depends_on:
#      db:
#        condition: service_healthy

volumes:
  pgdata:

networks:
  backend:
    driver: bridge