version: "3.8"

services:
  app:
    container_name: jira-app
    image: jira-app
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - ./prod.env
    depends_on:
      - db
      - nginx
    networks:
      - backend
  db:

    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./prod.env
    networks:
      - backend

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx//nginx.conf:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge
